### ISSUE TITLE
cannot connect when FTP Server behind firewall and router..

### ISSUE THREAD

**Issue by pnukeid** [NoxArt/SublimeText2-FTPSync#101]
i try connect ftp server behind router and firewall, using passive mode on filezilla and setting use external ip address instead on passive mode it's work.

and my question how use external ip address like on the filezilla setting on ftpsync ?

this is error i got..

FTPSync [default] > Connected to: 118.97.237.138:6001 (timeout: 60) (key: None)
FTPSync [default] > Logged in as: eka (using password: YES)
FTPSync [default] > Download of {.} failed [Exception: ]
## FTPSync > Exception in user code:

Traceback (most recent call last):
  File ".\FTPSync.py", line 1433, in execute
  File ".\ftpsyncwrapper.py", line 677, in list
  File ".\ftpsyncwrapper.py", line 782, in __execute
  File ".\ftpsyncwrapper.py", line 649, in action

**Comment by luizj** [comment]
I don't use proxy.

When I enable passive mode in filezilla server, i got the same error.

Filezilla passive ON, FTPSync passive ON: Download of {.} failed [Exception: 421 Could not create socket.]'

Filezilla passive ON, FTPSync passive OFF: i got time out.. Download of {.} failed [Exception: ]'
