### ISSUE TITLE
Maximum number of connections

### ISSUE THREAD

**Issue by StuartMorris0** [NoxArt/SublimeText2-FTPSync#154]
I am finding that FTPSync appears to open too many connections. I have seen previous issue referring to a similar issue - https://github.com/NoxArt/SublimeText2-FTPSync/issues/86

I am often getting this message:

```
FTPSync [default] > Login failed [Exception: 530 Sorry, the maximum number of clients (3) for this user are already connected.]
```

I have tried changing the max_threads to 1 in by Settings - Default file.   

Here is my FTPSync.sublime-settings file which is for this specific project/folders.

```
{
    "default": {
        "host": "",
        "username": "",  /
        "password": "",
        "path": "/public_html/",

        "upload_on_save": true,
         "download_on_open": true,
         "max_threads" : 1,
         "debug_threads" : true
    }
}
```

What appears to happen is some of the files/folders are downloaded then the error is received:

```
FTPSync [default] > Login failed [Exception: 530 Sorry, the maximum number of clients (3) for this user are already connected.]
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File ".\FTPSync.py", line 921, in makeConnection
  File ".\ftpsyncwrapper.py", line 331, in login
  File ".\ftpsyncwrapper.py", line 276, in retryingCommand
  File ".\ftpsyncwrapper.py", line 270, in call
  File ".\lib2\ftplib.py", line 385, in login
  File ".\lib2\ftplib.py", line 244, in sendcmd
  File ".\lib2\ftplib.py", line 219, in getresp
error_perm: 530 Sorry, the maximum number of clients (3) for this user are already connected.
```

**Comment by daCyberpunk** [comment]
Hi!
having the same issue right now. Is there any solution? 
Thx, Falk
