### ISSUE TITLE
ftpsync not work

### ISSUE THREAD

**Issue by chenny** [NoxArt/SublimeText2-FTPSync#187]
error_info:
Traceback (most recent call last):
  File "/Applications/Sublime Text 3.app/Contents/MacOS/sublime_plugin.py", line 460, in is_visible_
    ret = self.is_visible()
  File "FTPSync in /Users/duolong/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 3283, in is_visible
TypeError: 'NoneType' object is not subscriptable

**Comment by NoxArt** [comment]
Hi, after updating to the last version, can you let me know if it helped?

**Comment by calledT** [comment]
@NoxArt the issue was fixed on my st3 in window with the last verison

**Comment by chenny** [comment]
tks , ftpsync Can work.
flow:
try upgrade package, not work;
try remove package, and install package , aways not work ;
reinstall sublime 3 , ok

**Comment by NoxArt** [comment]
Glad to hear
