### ISSUE TITLE
Excpetion: 500 'AUTH': command unrecognized.

### ISSUE THREAD

**Issue by MCMainiac** [NoxArt/SublimeText2-FTPSync#193]
I have a problem when connecting to my  ftp server:
```
b"FTPSync [default] > Authentication failed [Exception: 500 'AUTH': command unrecognized.]"
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "FTPSync in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 972, in makeConnection
  File "ftpsyncwrapper in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 337, in authenticate
  File "ftpsyncwrapper in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 719, in auth
  File "lib3.ftplib in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 274, in voidcmd
  File "lib3.ftplib in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 248, in voidresp
  File "lib3.ftplib in C:\Users\Rico\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 243, in getresp
FTPSync.lib3.ftplib.error_perm: 500 'AUTH': command unrecognized.
```

Is is the way i configured the server? I checked my username and password twice.

**Comment by NoxArt** [comment]
Hi, I would say so. The error makes it seem that the code is correct but the server simply do not recognize this command. It's not a part of the vanilla FTP specification but a FTP Security Extension. It so much recommended to have this extension that I didn't even consider that it would not be present.
You mentioned configuration of **server** - does this mean not the server credentials, but the actual server? If it is so, please check if you can add this extension too. You can also take a look at not enforcing SSL_REUSE to allow secure transactions.

http://en.wikipedia.org/wiki/List_of_FTP_commands
http://tools.ietf.org/html/rfc2228

If you have this extension installed and properly configured, we can continue looking into it, but so far it seems this way.
