### ISSUE TITLE
Configuration File Won't Parse

### ISSUE THREAD

**Issue by Kelderic** [NoxArt/SublimeText2-FTPSync#200]
I can't get the settings file working. I've tried examples and several formats, and nothing works.

The example on packagecontrol.io is:
````
{
    'primary': {
        host: 'ftp.mywebsite.com',
        username: 'johnsmith',
        password: 'secretpassword',
        path: '/www/',

        upload_on_save: true,
        tls: true
    }
}
````
This gives an error of: Expecting Property name enclosed in double quotes. I then tried this:
````
{
    "primary": {
        host: "ftp.mywebsite.com",
        username: "johnsmith",
        password: "secretpassword",
        path: "/www/",

        upload_on_save: true,
        tls: true
    }
}
````
Same problem. I then tried this:
````
{
    "primary": {
        "host": "ftp.mywebsite.com",
        "username": "johnsmith",
        "password": "secretpassword",
        "path": "/www/",

        "upload_on_save": true,
        "tls": true
    }
}
````
The final one gets a new error. Expecting value, line 1.

**Comment by Kelderic** [comment]
I'm not sure if this will help, but I turned on debugging and got this:

During handling of the above exception, another exception occurred:
````
Traceback (most recent call last):
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 868, in loadConfig
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 760, in parseJson
  File "lib3.simplejson.decoder in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 373, in decode
  File "lib3.simplejson.decoder in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 403, in raw_decode
  File "lib3.simplejson.scanner in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 127, in scan_once
  File "lib3.simplejson.scanner in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 87, in _scan_once
FTPSync.lib3.simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------------------
Exception in thread Thread-47:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2653, in run
TypeError: 'NoneType' object is not subscriptable
````

**Comment by NoxArt** [comment]
Hi,
It is recommendable to use the "Setup FTPSync in this folder" menu option, which will create the base file for you, seeing how the file looks like I think you didn't go that way.

However your 3rd snippet is the way I expect it to look like and jsonlint reports this as a correct JSON. There is a slight pre-processing on FTPSync's part (allowing comments) so this is not 100 % conclusive.

Does the password contain any special characters? Maybe there's something that could break the syntax or the comments removal. Try setting it to null and see it that would work. Using null as password should actually work anyway, this should offer you to provide the password into an input instead of storing it inside a file.
(this actually applies to all the values in general, but password is among the more likely places for special characters and one that's understandably not presented in issues)

Lastly you can try adding

    "debug_extras": {
        "dump_config_load": true
    }

inside your "primary" { ... }, after "tls", then check the console. It should dump the config file after the manipulations so we can see if there's something wrong.

**Comment by Kelderic** [comment]
When I use the Setup from the menu, I get a much larger file with many commented out options. Without changing a single thing on this file, I get this error:
````
Exception: Expecting value: line 1 column 1 [char 0]
````
After adding the debug, I get this in the console:

````
Traceback (most recent call last):
  File "FTPSync in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 868, in loadConfig
  File "FTPSync in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 760, in parseJson
  File "lib3.simplejson.decoder in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 373, in decode
  File "lib3.simplejson.decoder in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 403, in raw_decode
  File "lib3.simplejson.scanner in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 127, in scan_once
  File "lib3.simplejson.scanner in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 87, in _scan_once
FTPSync.lib3.simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------------------
Exception in thread Thread-18:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "FTPSync in C:\Users\Andy\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2653, in run
TypeError: 'NoneType' object is not subscriptable
````

**Comment by Kelderic** [comment]
Something odd is going on here. I tried putting in my credentials again, from the generated file. If I try to save that settings file, I get the error. However, it is now working for other files. So it works for everything except it's own settings file. Might be worth it to add a more descriptive error message if the file title matches 'ftpsync.settings'.

**Comment by NoxArt** [comment]
I think it's more of a case that when you re-save the file it get's re-parsed and the cached config updated. And the error pertains to parsing this file, so other files will be fine.

Can you add this to Preferences > Package Settings > FTPSync > Settings - User

    {
        "debug_json": true
    }
(or just change this option to true in the Default, it won't survive package upgrade, but it's just for testing). Restart ST after this just to be sure.
This is actually a better debug config for this case than I mentioned. It will print the config after the pre-processing, right before it goes to JSON parser, so we can check if it didn't get broken on its way there.

**Comment by Kelderic** [comment]
After adding that to my user settings file, when I try to save the .settings file, I get this in the console:

````
b'FTPSync > Loading config: cache hit (key: C:\\websites\\webclerk\\www\\ftpsync.settings)'
{'password': 'MYPASSWORD', 'private_key_pass': None, 'upload_on_save': True, 'debug_extras': {'print_list_result': False, 'debug_remote_paths': False, 'debug_mfmt': False, 'debug_get_local_path': False, 'debug_put_error': False, 'after_save_watch': False, 'dump_config_load': True, 'print_ensure_folders': False}, 'always_sync_local_permissions': True, 'timeout': 30, 'file_path': 'C:\\websites\\webclerk\\www\\ftpsync.settings', 'default_local_permissions': 'auto', 'download_on_open': False, 'port': 21, 'after_save_watch': None, 'encoding': 'auto', 'passive': True, 'host': 'www.functionaldevices.com', 'set_remote_lastmodified': True, 'path': '/www/dev/', 'default_folder_permissions': '755', 'use_tempfile': True, 'private_key': None, 'tls': False, 'time_offset': 0, 'default_upload_permissions': None, 'ignore': None, 'upload_delay': 0, 'overwrite_newer_prevention': True, 'username': 'functi5'}
b'FTPSync > Failed parsing configuration file: {C:\\websites\\webclerk\\www\\ftpsync.settings} (commas problem?) [Exception: Expecting value: line 1 column 1 (char 0)]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "lib3.simplejson.scanner in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 85, in _scan_once
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 868, in loadConfig
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 760, in parseJson
  File "lib3.simplejson.decoder in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 373, in decode
  File "lib3.simplejson.decoder in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 403, in raw_decode
  File "lib3.simplejson.scanner in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 127, in scan_once
  File "lib3.simplejson.scanner in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 87, in _scan_once
FTPSync.lib3.simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------------------
Exception in thread Thread-4:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "FTPSync in C:\Users\User\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2653, in run
TypeError: 'NoneType' object is not subscriptable
````

Seems to be almost the same error as before adding the "debug_json".

**Comment by Kelderic** [comment]
After rebooting the computer, I now have this also:

````
b'FTPSync > Found no config for {C:\\Users\\User\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\Preferences.sublime-settings}'
b'FTPSync > Found no config for {C:\\Users\\User\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\Preferences.sublime-settings}'
b'FTPSync > Config not found for: C:\\Users\\User\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\Preferences.sublime-settings'
````

**Comment by NoxArt** [comment]
Yes, this is just a debug option to see more, it will not fix stuff by itself.
I'll look into this more when I get home.

As for the second message - this is completely normal, it just says that FTPSync doesn't see these mentioned files as belonging to some ftpsync.settings files so should not be managed. Which is expectable since I don't think you want to upload anything in the `C:\\Users\\User\\AppData\\Roaming\\Sublime Text 3\\Packages\\User\\`

**Comment by Kelderic** [comment]
Thanks. I appreciate you looking into this btw.

**Comment by NoxArt** [comment]
Hi, I have copy-pasted this snippet

    {
        "primary": {
            "host": "ftp.mywebsite.com",
            "username": "johnsmith",
            "password": "secretpassword",
            "path": "/www/",
    
            "upload_on_save": true,
            "tls": true
        }
    }

setting and it parses successfully for me (it of course laters failes to connect since it's an example).

What OS do you use? Maybe check charset / newline / BOM? I would try utf-8 / UNIX newlines / removing BOM.

Also, not sure we've seen the debug_json in use here, it should be something preceeded by "Debug JSON" printed in console, I don't see it here ... can you please check it? Thank you

**Comment by dimanyc** [comment]
@NoxArt  Looks like it is the OS charset issue. Default settings are also getting the same error if I try ti lint them as json (e.g. [http://jsonlint.com/](http://jsonlint.com/)). Ended up creating a new JSON file with an online JSON generator: [http://beta.json-generator.com/](http://beta.json-generator.com/)

**Comment by Lli-li** [comment]
Maybe is pretty late but, I could make it work on my machine, although my sublime solve the problem it self, it asked me to create Settings.sublime-syntax in YALM syntax in AppData/Roaming/Sublime Text 3/pakages/User/ folder and it started to works as if by magic. By the way I changed primary to default in my ftpsync.settings. 

I hope to help someone.
