### ISSUE TITLE
 Getting metadata failed

### ISSUE THREAD

**Issue by sunghwan2789** [NoxArt/SublimeText2-FTPSync#201]
b'FTPSync > Loading config: cache hit (key: D:\\Develop\\...\\index.html)'
b'FTPSync [default] > Connected to: ...:21 (timeout: 30) (key: ...)'
b'FTPSync [default] > Authentication processed'
b'FTPSync [default] > Logged in as: ... (using password: YES)'
b'FTPSync [default] > Getting metadata failed: {index.html} [Exception: ]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 778, in action
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 789, in retrlines
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 396, in transfercmd
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 770, in ntransfercmd
  File "./ssl.py", line 625, in wrap_socket
  File "./ssl.py", line 345, in __init__
  File "./ssl.py", line 341, in __init__
  File "./ssl.py", line 548, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FTPSync in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 1838, in execute
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 819, in list
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 949, in __execute
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 783, in action
FTPSync.ftpsyncexceptions.FileNotFoundException
------------------------------------------------------------
b'FTPSync > Closing connection'
b'FTPSync > Loading config: cache hit (key: D:\\Develop\\...\\index.html)'
b'FTPSync [default] > Connected to: ...:21 (timeout: 30) (key: ...)'
b'FTPSync [default] > Authentication processed'
b'FTPSync [default] > Logged in as: ... (using password: YES)'
b'FTPSync [default] > Upload failed: {index.html} [Exception: 425 Cannot open data connection.]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 430, in action
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 809, in storbinary
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 396, in transfercmd
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 770, in ntransfercmd
  File "./ssl.py", line 625, in wrap_socket
  File "./ssl.py", line 345, in __init__
  File "./ssl.py", line 341, in __init__
  File "./ssl.py", line 548, in do_handshake
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:550)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "FTPSync in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 1421, in action
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 467, in put
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 949, in __execute
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 441, in action
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 1104, in __ensurePath
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 601, in cwd
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 274, in voidcmd
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 248, in voidresp
  File "lib3.ftplib in C:\Portable\Sublime Text\Data\Installed Packages\FTPSync.sublime-package", line 241, in getresp
FTPSync.lib3.ftplib.error_temp: 425 Cannot open data connection.
------------------------------------------------------------
b'FTPSync > Closing connection'

and my connection config is
{
	"default": {
		"host": "...",
		"username": "...",
		"password": null,
		"path": "/www/.../",

		"upload_on_save": true,
		"tls": true,
	}
}

**Comment by sunghwan2789** [comment]
I use special characters in password. like ^, (
does it matter?
