### ISSUE TITLE
FTPSync > Failed parsing configuration file

### ISSUE THREAD

**Issue by guicastro** [NoxArt/SublimeText2-FTPSync#202]
I was installed FTPSync on Sublime Text 2, using Package Control.

I configured my project folder to use FTPSync, right-click, FTPSync -> Setup FTPSync in this folder.

After i change values (host, user pass) and save the file ftpsync.settings, but after save, on console window, the follow message appears and FTPSync not working.

FTPSync > Failed parsing configuration file: {/Users/guilherme/Sites/frenlog/ftpsync.settings} (commas problem?) [Exception: Expecting value: line 1 column 1 (char 0)]
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "./FTPSync.py", line 868, in loadConfig
  File "./FTPSync.py", line 760, in parseJson
  File "./lib2/simplejson/decoder.py", line 373, in decode
  File "./lib2/simplejson/decoder.py", line 403, in raw_decode
  File "./lib2/simplejson/scanner.py", line 127, in scan_once
  File "./lib2/simplejson/scanner.py", line 87, in _scan_once
JSONDecodeError: Expecting value: line 1 column 1 (char 0)
------------------------------------------------------------
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "./FTPSync.py", line 2653, in run
TypeError: 'NoneType' object is unsubscriptable

-----------------

Here is my ftpsync.settings

{
	// HELP / INFO moved to bottom
	// Remove "//" to uncomment settings directive

	"default": {

		"host": "ftp.frenlog.com.br",
		"username": "frenlog",  // or null for anonymous login
		"password": "xxxxxxxxx",
		"path": "/",

		"upload_on_save": false, // set *false* if you do not want to upload on save!

		// "port": 21,
		// "tls": false,
		// "timeout": 30, // [seconds]

		// "passive": true,
		// "download_on_open": false,
		// "overwrite_newer_prevention": true,
		// "default_folder_permissions": "755",
		// "default_upload_permissions": null, // null = no action taken
		// "time_offset": 0, // [seconds]
		// "always_sync_local_permissions": true,

		// Value "auto" = use UTF-8 if availible (FEAT: UTF8), otherwise use local
		// "encoding": "auto",

		// Trade small performance impact for more stable and secure transfer (old file is intact until the download is finished)
		// "use_tempfile": true,

		// Regular expression, recommending using \b in general and /.../ for folders to avoid matching substrings
		// "ignore": "",

		// Can be used for increase of performance or to allow build scripts to finish
		// "upload_delay": 0, // [seconds]

		// Only if the server has MFMT extension installed
		// "set_remote_lastmodified": true,

		// Chmod value for files newly downloaded by FTPSync
		//   "auto" = same as on server
		//   null = no action taken
		//   "0644" = example for direct value
		// "default_local_permissions": "auto",

		// List of lists with pathnames and filenames to folders to be watched for change in between delay (upload_delay)
		//   example: after_save_watch: [ [ "code/assets/css", "*.css" ], [ "code/assets/", "*.jpg, *.png, *.gif" ] ]
		//   used only in conjunction with upload_on_save and upload_delay **
		// For more info see https://github.com/NoxArt/SublimeText2-FTPSync/wiki/Why-and-how-to-use-afterwatch
		// "after_save_watch": [],

	}

	// ------ INFO ----------------------------------------------------------------------

	// Index page
	// --- https://github.com/NoxArt/SublimeText2-FTPSync/

	// For settings description see:
	// --- https://github.com/NoxArt/SublimeText2-FTPSync/wiki/All-settings

	// For more info see:
	// --- https://github.com/NoxArt/SublimeText2-FTPSync/wiki/_pages

	// Want to ask? Report a bug?
	// --- Hit: https://github.com/NoxArt/SublimeText2-FTPSync/issues/new

	// ** Commas **

	// from now on extra commas are allowed and recommended

	// ** Comments **

	// The "//" are so called "comments", all text after it is ignored,
	// they are used for notes or deactivating an entry

	// Non-basic settings are deactivated and default options specified in the global settings file,
	// that is $packages$/FTPSync/ftpsync.sublime-settings (where $packages$ is a path where Sublime
	// keeps packages in your Operating System) accessible via Preferences > Package Settings > FTPSync
	// Use Settings - User to override the global defaults

	// More info about Sublime Text 2 settings on http://www.sublimetext.com/docs/2/settings.html

}

**Comment by NoxArt** [comment]
Hi,
what OS and Sublime version do you have?

If you change `"debug_json"` in Preferences > Package Settings > FTPSync > Settings - Default to **true**, restart Sublime and try to do an action with FTPSync, can you post what is in the console after message `Debug JSON:` ? (you can clear out password)

**Comment by mvofreire** [comment]
I have the same problem..

Error on parssing configuration file in sublime 3, comma problem? #221

**Comment by guicastro** [comment]
mvofreire maybe comma problem. I reinstall and reconfigure ftpsync.settings.

**Comment by mvofreire** [comment]
@guicastro tanks for reply.. I tested you suggest and works..

**Comment by OscarEriksen** [comment]
This is still an issue. Please fix. Tried reinstall and reconfigure to no avail.
