### ISSUE TITLE
Getting metadata failed

### ISSUE THREAD

**Issue by ArturGabrys** [NoxArt/SublimeText2-FTPSync#208]
Hi,
Thank you very much for great job with FTPSync. Today I've noticed some problems with uploading files, till today everything was working great. Here's what Sublime console shows:

```
FTPSync > Loading config: cache hit (key: I:\webfiles\file.tpl)
Writing file /I/webfiles/file.tpl with encoding UTF-8
FTPSync [default] > Connected to: SERVER_IP:21 (timeout: 30) (key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
FTPSync [default] > Logged in as: LOGIN (using password: YES)
FTPSync [default] > Getting metadata failed: {webfiles\file.tpl} [Exception: ]
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File ".\FTPSync.py", line 1838, in execute
  File ".\ftpsyncwrapper.py", line 819, in list
  File ".\ftpsyncwrapper.py", line 949, in __execute
  File ".\ftpsyncwrapper.py", line 783, in action
FileNotFoundException
------------------------------------------------------------
FTPSync > Closing connection
FTPSync > Loading config: cache hit (key: I:\webfiles\file.tpl)
Writing file /I/webfiles/file.tpl with encoding UTF-8
FTPSync [default] > Connected to: SERVER_IP:21 (timeout: 30) (key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx)
FTPSync [default] > Logged in as: LOGIN (using password: YES)
FTPSync [default] > Upload failed: {webfiles\file.tpl} [Exception: 'ascii' codec can't decode byte 0xf3 in position 16: ordinal not in range(128)]
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File ".\FTPSync.py", line 1466, in execute
  File ".\FTPSync.py", line 1454, in action
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf3 in position 16: ordinal not in range(128)
------------------------------------------------------------
FTPSync > Closing connection
```

I've tried reinstall package but still get this error.

Thank you!

**Comment by antimatterES** [comment]
Try to change TLS to false.
It worked for me!

**Comment by ArturGabrys** [comment]
OK, so the problem was that on the server I've had blocked ports needed for passive ftp connection.

Thank you.

**Comment by NoxArt** [comment]
Glad it's resolved! and thanks antimatterES for helping out

I wonder if something like this can be detected, the returned error messages aren't really exact about the issue

**Comment by ArturGabrys** [comment]
Well the information "timeout" should give me thinking. Timeout return when server is down or ports are blocked. Server was working OK, so I should check the ports.

I used iptables to allow ports for passive ftp connection, in my case:

```
iptables -A INPUT -p tcp --dport 49160:49200 -j ACCEPT 
iptables -A INPUT -p udp --dport 49160:49200 -j ACCEPT 
```
