### ISSUE TITLE
Exception: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE

### ISSUE THREAD

**Issue by helderfcs** [NoxArt/SublimeText2-FTPSync#209]
Hello,

  I'm getting the following error when saving and uploading a file to a vsftpd server configured with TLS:

`FTPSync [default] > Authentication failed [Exception: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:550)]`
`FTPSync > Exception in user code:`
`------------------------------------------------------------`
`Traceback (most recent call last):`
`  File "FTPSync in /Users/helderfcs/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 972, in makeConnection`
`  File "ftpsyncwrapper in /Users/helderfcs/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 337, in authenticate`
`  File "ftpsyncwrapper in /Users/helderfcs/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 290, in retryingCommand`
`  File "ftpsyncwrapper in /Users/helderfcs/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 284, in call`
`  File "lib3.ftplib in /Users/helderfcs/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 727, in auth`
`  File "./ssl.py", line 625, in wrap_socket`
`  File "./ssl.py", line 345, in __init__`
`  File "./ssl.py", line 341, in __init__`
`  File "./ssl.py", line 548, in do_handshake`
`ssl.SSLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:550)`

  Any idea why this is happening ?

Thank you

**Comment by LoisBritto** [comment]
I'm having the same problem.

**Comment by steevec** [comment]
Same for me :p

**Comment by alinneacsu** [comment]
The same problem here
