### ISSUE TITLE
Can get any file

### ISSUE THREAD

**Issue by mato777** [NoxArt/SublimeText2-FTPSync#220]
i downloaded the plugin using package control. 
In the console i get:
Exception in thread Thread-5:
Traceback (most recent call last):
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 778, in action
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 456, in retrlines
  File "lib3.ftplib in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 396, in transfercmd
  File "lib3.ftplib in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 356, in ntransfercmd
  File "lib3.ftplib in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 334, in makepasv
  File "lib3.ftplib in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 877, in parse227
FTPSync.lib3.ftplib.error_reply: 220 Firewall Authentication required before proceeding with service

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "FTPSync in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2946, in run
  File "FTPSync in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2098, in execute
  File "FTPSync in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2152, in listFiles
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 819, in list
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 949, in __execute
  File "ftpsyncwrapper in C:\Users\raulmatias\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 783, in action
FTPSync.ftpsyncexceptions.FileNotFoundException

b'FTPSync > Closing connection'

and no result at all.  Can´t do anything.

**Comment by NoxArt** [comment]
Hi,
"**Firewall Authentication** required before proceeding with service"

Either on your hosting's side or your PC there's a firewall, that needs to be configured so that Sublime Text can send requests through...
