### ISSUE TITLE
Can`t work with FTP (Broken pipe)

### ISSUE THREAD

**Issue by Zelvar** [NoxArt/SublimeText2-FTPSync#222]
Hello, I have this issue with FTPSync, When I want download / upload file. It worked for about 10 times and then it stopped..

I am using Sublime Text 3 on Mac OS X (10.11.3).

Any Ideas? Thank you. :-)

Console output:
`FTPSync > Command voidcmd timed out, retrying (4 remaining)...
Exception in thread Thread-49:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "FTPSync in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 2789, in run
  File "ftpsyncworker in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 148, in addCommand
  File "ftpsyncworker in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 164, in __run
  File "ftpsyncworker in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 125, in fillConnection
  File "FTPSync in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 1025, in makeConnection
  File "ftpsyncwrapper in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 702, in cwd
  File "ftpsyncwrapper in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 327, in _makePassive
  File "ftpsyncwrapper in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 273, in voidcmd
  File "lib3.ftplib in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 202, in putcmd
  File "lib3.ftplib in /Users/Zelvar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 197, in putline
BrokenPipeError: [Errno 32] Broken pipe`

**Comment by NoxArt** [comment]
Hi,
thank you for reporting

If this continues to be an issue, in the meantime please try to put

    {
        "max_threads": 1
    }

to Preferences > Package Settings > FTPSync > Settings - user
