### ISSUE TITLE
FTPSync > Failed parsing configuration file

### ISSUE THREAD

**Issue by ImSeaWorld** [NoxArt/SublimeText2-FTPSync#233]
I've looked at all the issues that mimic mine and I haven't found the answer surprisingly. The last time I used this it worked 100% and since I reinstalled windows on a new HDD and now everything doesn't work. I also reinstalled FTPSync and still nothing.

Using: Sublime Text 3 (Build 3103)

`{
	"default": {
		"host": "mydomain.com",
		"username": "ftpsync@mydomain.com",
		"password": "supersecretpassword",
		"path": "/",
		"upload_on_save": true,
		"port": 21
	}
}`

I put it in JSONLint and it's valid. I already knew it was, but just because I've seen it asked on numerous threads.

Debug Output:

> FTPSync > Failed parsing configuration file: {C:\\Users\\SeaWorld\\Documents\\Web Dev\\LMA.Online\\Admin Panel\\ftpsync.settings} (commas problem?) [Exception: Expecting value: line 1 column 1 (char 0)]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "lib3.simplejson.scanner in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 85, in _scan_once
IndexError: string index out of range

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
>  File "FTPSync in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 868, in loadConfig
>  File "FTPSync in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 760, in parseJson
>  File "lib3.simplejson.decoder in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 373, in decode
>  File "lib3.simplejson.decoder in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 403, in raw_decode
>  File "lib3.simplejson.scanner in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 127, in scan_once
>  File "lib3.simplejson.scanner in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 87, in _scan_once
>FTPSync.lib3.simplejson.scanner.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
>------------------------------------------------------------
>Exception in thread Thread-18:
>Traceback (most recent call last):
>  File "./threading.py", line 901, in _bootstrap_inner
>  File "FTPSync in C:\Users\SeaWorld\AppData\Roaming\Sublime Text 3\Installed Packages\FTPSync.sublime-package", line 2653, in run
>TypeError: 'NoneType' object is not subscriptable

**Comment by raedlime** [comment]
Unfortunately same here :-/ Worked fine 'till yesterday morning. But since then, no chance to get connection to server at all.

**Comment by OscarEriksen** [comment]
Same here. We're having this issue and it's an **extremely** annoying thing to have. Spent a day on this now. Can you please release a fix immediately?

**Comment by devmath** [comment]
Hey guys. I'm too having this problem. First time I use this plugin and doesn't work :-/

**Comment by cybrox** [comment]
Sadly have to confirm this, I've been using this for definitely more than a year and now it's fully broken 😢

**Comment by NoxArt** [comment]
Hi, I've tried to address this to a limited degree.
Unfortunately there never been any clear-cut "steps to reproduce" (it always worked on my end, multiple machines), so I'm working rather blind so far. I have added some checks and retry mechanism, hopefully it helps. If not, please try to enable debugJson in the global settings (accessible from Menu > Preferences > Package Settings)
Thank you
