### ISSUE TITLE
Can't load plugin

### ISSUE THREAD

**Issue by Tadasb** [NoxArt/SublimeText2-FTPSync#235]
Console error:
` File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/ftpsyncwrapper.py", line 53, in <module>
    import FTPSync.lib3.ftplib as ftplib
ImportError: No module named 'FTPSync'`

**Comment by NoxArt** [comment]
Hi,
have you tried restarting Sublime Text? What version of Sublime Text and OS do you have?

**Comment by Tadasb** [comment]
I update sublime-text now to build 3114 but still got the same error:
`reloading plugin SublimeText2-FTPSync.__init__
reloading plugin SublimeText2-FTPSync.FTPSync
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/FTPSync.py", line 63, in <module>
    import FTPSync.lib3.simplejson as json
ImportError: No module named 'FTPSync'
reloading plugin SublimeText2-FTPSync.ftpsynccommon
reloading plugin SublimeText2-FTPSync.ftpsyncexceptions
reloading plugin SublimeText2-FTPSync.ftpsyncfiles
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/ftpsyncfiles.py", line 45, in <module>
    from FTPSync.ftpsynccommon import Types
ImportError: No module named 'FTPSync'
reloading plugin SublimeText2-FTPSync.ftpsyncfilewatcher
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/ftpsyncfilewatcher.py", line 43, in <module>
    from FTPSync.ftpsyncfiles import gatherMetafiles, getChangedFiles
ImportError: No module named 'FTPSync'
reloading plugin SublimeText2-FTPSync.ftpsyncprogress
reloading plugin SublimeText2-FTPSync.ftpsyncpubsub
reloading plugin SublimeText2-FTPSync.ftpsyncworker
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/ftpsyncworker.py", line 41, in <module>
    from FTPSync.ftpsynccommon import Types
ImportError: No module named 'FTPSync'
reloading plugin SublimeText2-FTPSync.ftpsyncwrapper
Traceback (most recent call last):
  File "/Applications/Sublime Text 2.app/Contents/MacOS/sublime_plugin.py", line 78, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Tadas/Library/Application Support/Sublime Text 3/Packages/SublimeText2-FTPSync/ftpsyncwrapper.py", line 53, in <module>
    import FTPSync.lib3.ftplib as ftplib
ImportError: No module named 'FTPSync'
plugins loaded`
