### ISSUE TITLE
"Setup FTPSync in this folder" fails on clean ST3 installation

### ISSUE THREAD

**Issue by denizdogan** [NoxArt/SublimeText2-FTPSync#237]
Started a fresh portable ST3 on Windows 10, installed Package Control as usual, restarted ST3, installed FTPSync, ran "Setup FTPSync in this folder". Nothing happens, View Console says:

```
Traceback (most recent call last):
  File "D:\_temp\sublime_plugin.py", line 551, in run_
    return self.run(**args)
  File "FTPSync in D:\_temp\Data\Installed Packages\FTPSync.sublime-package", line 3001, in run
  File "./python3.3/ntpath.py", line 256, in dirname
  File "./python3.3/ntpath.py", line 220, in split
  File "./python3.3/ntpath.py", line 162, in splitdrive
TypeError: object of type 'NoneType' has no len()
```

What could be the issue?

**Comment by denizdogan** [comment]
No longer relevant to me, closing
