### ISSUE TITLE
global name 're_ignore' is not defined 

### ISSUE THREAD

**Issue by polearnik** [NoxArt/SublimeText2-FTPSync#238]
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 252, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "FTPSync in /home/polearnik/.config/sublime-text-3/Installed Packages/FTPSync.sublime-package", line 2599, in on_load
NameError: global name 're_ignore' is not defined
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 231, in run_callback
    expr()
  File "/opt/sublime_text/sublime_plugin.py", line 252, in <lambda>
    run_callback('on_load', callback, lambda: callback.on_load(v))
  File "FTPSync in /home/polearnik/.config/sublime-text-3/Installed Packages/FTPSync.sublime-package", line 2599, in on_load

**Comment by comlaterra** [comment]
Mmm, not a single answer? a link somewhere?
