### ISSUE TITLE
FTPSync not uploading (with different errors)

### ISSUE THREAD

**Issue by OscarEriksen** [NoxArt/SublimeText2-FTPSync#242]
Bogus issue - my bad

**Comment by OscarEriksen** [comment]
Further errors:

`Traceback (most recent call last):
  File "FTPSync in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 1004, in makeConnection
  File "ftpsyncwrapper in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 318, in connect
  File "ftpsyncwrapper in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 307, in retryingCommand
  File "ftpsyncwrapper in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in /Users/Oscar/Library/Application Support/Sublime Text 3/Installed Packages/FTPSync.sublime-package", line 158, in connect
  File "./python3.3/socket.py", line 435, in create_connection
  File "./python3.3/socket.py", line 426, in create_connection
TimeoutError: [Errno 60] Operation timed out
`

**Comment by OscarEriksen** [comment]
@NoxArt Please fix. FTPSync is broken

**Comment by OscarEriksen** [comment]
Tried from different WiFis, different computers, different servers
