### ISSUE TITLE
[Errno 11001] getaddrinfo failed

### ISSUE THREAD

**Issue by s-meiser** [NoxArt/SublimeText2-FTPSync#255]
Hi there,

i can't upload any files after a system reboot. 

Log when i save the setting file
```
b'FTPSync > Loading config: cache hit (key: C:\\Users\\werbecenter\\Desktop\\xampp\\htdocs\\DEKOLI\\ftpsync.settings)'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "FTPSync in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 751, in parseJson
  File "FTPSync in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 807, in parseJsonInternal
OSError: Content read from C:\Users\werbecenter\Desktop\xampp\htdocs\DEKOLI\ftpsync.settings is empty
------------------------------------------------------------
b'FTPSync > Retrying reading config... (remaining 2)'
b'FTPSync [default] > Connected to: 91.198.21.50:21 (timeout: 30) (key: e5a0c219e2dbf40b0626a8672506812c)'
b'FTPSync [default] > Logged in as: web38 (using password: YES)'
b'FTPSync > Closing connection'
b'FTPSync > Loading config: cache hit (key: C:\\Users\\werbecenter\\Desktop\\xampp\\htdocs\\DEKOLI\\ftpsync.settings)'
b'FTPSync > File globally ignored: {ftpsync.settings}'
b'FTPSync > Cancelling SyncCommandUpload [C:\\Users\\werbecenter\\Desktop\\xampp\\htdocs\\DEKOLI\\ftpsync.settings]: command is closed'
```

Log when i save a file
```
b'FTPSync [default] > Connection failed [Exception: [Errno 11001] getaddrinfo failed]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "FTPSync in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 1004, in makeConnection
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 318, in connect
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 158, in connect
  File "./python3.3/socket.py", line 417, in create_connection
socket.gaierror: [Errno 11001] getaddrinfo failed
------------------------------------------------------------
b'FTPSync > Loading config: cache hit (key: C:\\Users\\werbecenter\\Desktop\\xampp\\htdocs\\DEKOLI\\components\\com_jshopping\\templates\\vina_erida\\product\\dekoli_designer\\canvas_object.php)'
b'FTPSync [default] > Connection failed [Exception: [Errno 11001] getaddrinfo failed]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "FTPSync in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 1004, in makeConnection
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 318, in connect
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 290, in retryingCommand
  File "ftpsyncwrapper in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 284, in call
  File "lib3.ftplib in C:\Users\werbecenter\Documents\Sublime Text Build 3103 x64\Data\Installed Packages\FTPSync.sublime-package", line 158, in connect
  File "./python3.3/socket.py", line 417, in create_connection
socket.gaierror: [Errno 11001] getaddrinfo failed
------------------------------------------------------------
```

By the way: in filezilla works perfectly

Greetings
Sebastian

**Comment by sugardaddy** [comment]
I fixed my issue by doing the following.  Mine is Win 10 and sT3, but I'll bet solution is same.

It seems that the problem was that ST was not running as from administrator when the plugin was installed.

So uninstall the plugin, then restart ST.  Then start ST via the "Run as Admin" right click option.  Then install the plugin again.

hope this helps
