### ISSUE TITLE
not upload local folders if the server without

### ISSUE THREAD

**Issue by jcleng** [NoxArt/SublimeText2-FTPSync#270]
can not upload local folders if the server without,and say :No such file or directory.
must be make folder in the ftp server them after can upload the file.
Is it like this always?or not

**Comment by NoxArt** [comment]
Hi, should be possible, there's also a setting for permissions for such newly created folders:
default_folder_permissions

https://github.com/NoxArt/SublimeText2-FTPSync/wiki/All-settings

check the console if something else hasn't gone wrong in the process

**Comment by jcleng** [comment]
`b'FTPSync > Loading config: cache hit (key: C:\\Users\\Administrator\\Desktop\\demo\\777\\777)'
b'FTPSync [default] > Connected to: 182.254.229.91:21 (timeout: 30) (key: b74ab9e71426592c08dfe96ac0b86c06)'
b'FTPSync [default] > Logged in as: lxx (using password: YES)'
b'FTPSync [default] > Upload failed: {777\\777} [Exception: 550 Could not change perms on 777: No such file or directory]'
FTPSync > Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 430, in action
    self.retryingCommand('storbinary', [command, uploaded, transferBlocksize, perBlock])
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 290, in retryingCommand
    result = call()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 284, in call
    return getattr(self.connection, command)(*args)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 486, in storbinary
    with self.transfercmd(cmd, rest) as conn:
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 396, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 380, in ntransfercmd
    resp = self.sendcmd(cmd)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 269, in sendcmd
    return self.getresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 243, in getresp
    raise error_perm(resp)
FTPSync.lib3.ftplib.error_perm: 553 Can't open that file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 1121, in __ensurePath
    self.cwd(folder)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 703, in cwd
    self.retryingCommand('cwd', [path])
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 290, in retryingCommand
    result = call()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 284, in call
    return getattr(self.connection, command)(*args)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 601, in cwd
    return self.voidcmd(cmd)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 274, in voidcmd
    return self.voidresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 248, in voidresp
    resp = self.getresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 243, in getresp
    raise error_perm(resp)
FTPSync.lib3.ftplib.error_perm: 550 Can't change directory to 777: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 1127, in __ensurePath
    self.retryingCommand('mkd', [self.__encode(folder)])
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 290, in retryingCommand
    result = call()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 284, in call
    return getattr(self.connection, command)(*args)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 613, in mkd
    resp = self.voidcmd('MKD ' + dirname)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 274, in voidcmd
    return self.voidresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 248, in voidresp
    resp = self.getresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 243, in getresp
    raise error_perm(resp)
FTPSync.lib3.ftplib.error_perm: 550 Can't create directory: Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\FTPSync.py", line 1468, in action
    connection.put(self.file_path)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 467, in put
    return self.__execute(action)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 949, in __execute
    result = callback()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 444, in action
    self.__ensurePath(path)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 1131, in __ensurePath
    self.chmod(folder, self.config['default_folder_permissions'])
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 850, in chmod
    self.voidcmd(command)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 720, in voidcmd
    self.retryingCommand('voidcmd', [self.__encode(command)])
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 290, in retryingCommand
    result = call()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\ftpsyncwrapper.py", line 284, in call
    return getattr(self.connection, command)(*args)
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 274, in voidcmd
    return self.voidresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 248, in voidresp
    resp = self.getresp()
  File "D:\Sublime Text Build 3170\Data\Packages\FTPSync\lib3\ftplib.py", line 243, in getresp
    raise error_perm(resp)
FTPSync.lib3.ftplib.error_perm: 550 Could not change perms on 777: No such file or directory
------------------------------------------------------------`
@NoxArt console show this

**Comment by jcleng** [comment]
okey，i checked over ,its ftp user jurisdiction ,set root:root is ok
